name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: CMake
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=$(which clang++)
      - name: Build Chip8
        run: make -j
        working-directory: build