name: Build

on: push

jobs:
    build-linux-x11-clang:
        name: X11 (Linux, Clang)
        runs-on: ubuntu-latest
        env:
            CC: clang
            CFLAGS: -Werror
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  sudo apt update
                  sudo apt install llibx11-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxrandr-dev libxext-dev libxcursor-dev libxinerama-dev libxi-dev
            - name: CMake
              run: cmake -S . -B build -DCMAKE_CXX_COMPILER=$(which clang++)
            - name: Build CHIP8
              run: make chip8_emulator -j